variables:
  scale: [2, 8]
  brick_color: '#b11b00dc'
pipeline:
  - shader: brick_shape.glsl
    inputs:
      - src: memory
        uniform: scale
        name: scale
    output:
      dst: memory
      name: brick_shape
      width: 512
      height: 512
      # preview: simple
  - shader: brick_paint.glsl
    # debug_shader: out/debug_2.glsl
    inputs:
      - src: memory
        uniform: scale
        name: scale
      - src: memory
        uniform: brick_color
        name: brick_color
      - src: memory
        name: brick_shape
        uniform: brick_shape
    output:
      dst: memory
      name: out/result.png
      width: 512
      height: 512
      preview: simple
