pipeline:
  - shader: shader_1.frag
    inputs:
      - type: file
        name: markup.png
        uniform: markup
    output:
      type: memory
      name: noise_1 
  - shader: shader_2.frag
    inputs:
      - type: memory
        name: noise_1
        uniform: noise
    output:
      type: file
      name: result.png
