pipeline:
  - shader: brick_shape.glsl
    debug_shader: out/brick_shape.glsl
    inputs: []
    output:
      type: memory
      name: brick_shape
      width: 512
      height: 512
      preview: simple
  - shader: brick_paint.glsl
    # debug_shader: out/debug_2.glsl
    inputs:
      - type: memory
        name: brick_shape
        uniform: brick_shape
    output:
      type: file
      name: out/result.png
      width: 512
      height: 512
      preview: simple
